name: BiomeCompass
version: 1.0.0
description: Find biomes anywhere in any dimension!
author: rusthero
website: https://github.com/rusthero/BiomeCompass

api-version: 1.16
main: dev.rusthero.biomecompass.BiomeCompass

permissions:
  biomecompass.*:
    children:
      biomecompass.craft: true
      biomecompass.use: true
  biomecompass.craft:
    description: Allows crafting a new biome compass.
    default: true
  biomecompass.use:
    description: Allows using the biome compass.
    default: true